### ISSUE TITLE
[AbiRegistry.create] Cannot map the type "<name>" to a known type

### ISSUE THREAD

**Issue by chvarkov** [multiversx/mx-sdk-js-core#237]
Hi, I getting error when trying create Abi from json.
Looks like it cannot map enum, but it was working fine with another abi json's
I'm using @elrondnetwork/erdjs v11.1.0

```
core.js:6498 ERROR Error: Uncaught (in promise): Error: Cannot map the type "Status" to a known type
Error: Cannot map the type "Status" to a known type
    at TypeMapper.mapType (typeMapper.js:116:1)
    at typeMapper.js:157:1
    at Array.map (<anonymous>)
    at TypeMapper.mappedFields (typeMapper.js:157:1)
    at TypeMapper.mapStructType (typeMapper.js:147:1)
    at TypeMapper.mapRecursiveType (typeMapper.js:134:1)
    at TypeMapper.mapType (typeMapper.js:106:1)
    at AbiRegistry.remapToKnownTypes (abiRegistry.js:117:1)
    at AbiRegistry.create (abiRegistry.js:37:1)
    at app.component.ts:308:38
    at resolvePromise (zone.js:1211:1)
    at zone.js:1118:1
    at zone.js:1134:1
    at asyncGeneratorStep (asyncToGenerator.js:6:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1429:1)
    at asyncToGenerator.js:21:1
    at AppComponent.ngOnInit (app.component.ts:29:16)
    at callHook (core.js:2538:1)
```

Code to reporduce

```typescript
const abiJson = {
	"buildInfo": {
		"rustc": {
			"version": "1.66.0-nightly",
			"commitHash": "2019147c5642c08cdb9ad4cacd97dd1fa4ffa701",
			"commitDate": "2022-09-19",
			"channel": "Nightly",
			"short": "rustc 1.66.0-nightly (2019147c5 2022-09-19)"
		},
		"contractCrate": {
			"name": "loan-data",
			"version": "0.0.0",
			"git_version": "d1f960a-modified"
		},
		"framework": {
			"name": "elrond-wasm",
			"version": "0.35.0"
		}
	},
	"name": "LoanDataContract",
	"constructor": {
		"inputs": [],
		"outputs": []
	},
	"endpoints": [
		{
			"name": "getById",
			"mutability": "readonly",
			"inputs": [
				{
					"name": "id",
					"type": "BigUint"
				}
			],
			"outputs": [
				{
					"type": "LoanInfo"
				}
			]
		},
		{
			"name": "getList",
			"mutability": "readonly",
			"inputs": [
				{
					"name": "page",
					"type": "u64"
				},
				{
					"name": "size",
					"type": "u16"
				}
			],
			"outputs": [
				{
					"type": "variadic<LoanShortInfo>",
					"multi_result": true
				}
			]
		},
		{
			"name": "create",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "data",
					"type": "LoanCreateOptions"
				}
			],
			"outputs": [
				{
					"type": "LoanInfo"
				}
			]
		},
		{
			"name": "createByArgs",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "amount",
					"type": "BigUint"
				},
				{
					"name": "loaner_address",
					"type": "Address"
				},
				{
					"name": "token",
					"type": "EgldOrEsdtTokenIdentifier"
				},
				{
					"name": "status",
					"type": "Status"
				},
				{
					"name": "note",
					"type": "bytes"
				}
			],
			"outputs": [
				{
					"type": "LoanInfo"
				}
			]
		},
		{
			"name": "updateStatus",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "id",
					"type": "BigUint"
				},
				{
					"name": "status",
					"type": "Status"
				}
			],
			"outputs": [
				{
					"type": "Status"
				}
			]
		},
		{
			"name": "setArrayOfStruct",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "list",
					"type": "variadic<Item>",
					"multi_arg": true
				}
			],
			"outputs": []
		},
		{
			"name": "setArrayOfAddresses",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "list",
					"type": "variadic<Address>",
					"multi_arg": true
				}
			],
			"outputs": []
		},
		{
			"name": "setArrayOfBigInt",
			"mutability": "mutable",
			"inputs": [
				{
					"name": "list",
					"type": "variadic<BigInt>",
					"multi_arg": true
				}
			],
			"outputs": []
		}
	],
	"events": [],
	"hasCallback": false,
	"types": {
		"Item": {
			"type": "struct",
			"fields": [
				{
					"name": "amount",
					"type": "BigUint"
				},
				{
					"name": "address",
					"type": "Address"
				}
			]
		},
		"LoanCreateOptions": {
			"type": "struct",
			"fields": [
				{
					"name": "amount",
					"type": "BigUint"
				},
				{
					"name": "loaner_address",
					"type": "Address"
				},
				{
					"name": "token",
					"type": "EgldOrEsdtTokenIdentifier"
				},
				{
					"name": "status",
					"type": "Status"
				},
				{
					"name": "note",
					"type": "bytes"
				}
			]
		},
		"LoanInfo": {
			"type": "struct",
			"fields": [
				{
					"name": "id",
					"type": "BigUint"
				},
				{
					"name": "amount",
					"type": "BigUint"
				},
				{
					"name": "loaner_address",
					"type": "Address"
				},
				{
					"name": "token",
					"type": "EgldOrEsdtTokenIdentifier"
				},
				{
					"name": "timestamp",
					"type": "u64"
				},
				{
					"name": "status",
					"type": "Status"
				},
				{
					"name": "note",
					"type": "bytes"
				}
			]
		},
		"LoanShortInfo": {
			"type": "struct",
			"fields": [
				{
					"name": "id",
					"type": "BigUint"
				},
				{
					"name": "amount",
					"type": "BigUint"
				},
				{
					"name": "loaner_address",
					"type": "Address"
				},
				{
					"name": "token",
					"type": "EgldOrEsdtTokenIdentifier"
				}
			]
		},
		"Status": {
			"type": "enum",
			"variants": [
				{
					"name": "Redeemed",
					"discriminant": 0
				},
				{
					"name": "NotRedeemed",
					"discriminant": 1
				}
			]
		}
	}
};

const scAbi = new SmartContractAbi(AbiRegistry.create(abiJson));

console.log('scAbi', scAbi);
```

**Comment by nvergez** [comment]
Hi, PR #224 fixes this issue and will be released in erdjs 12.

**Comment by chvarkov** [comment]
Just in case, if someone have this issue and you need to quickfix it before release v12 then you can move your dependent types after independents in property "types" of abi json.
In my case it was enums so I sort types to move enums before structs.

```
	const types = Object.entries(abiJson.types)
		.sort(([key, value]) => value.type !== 'enum' ? 1 : -1)
		.map(([key, value]) => ({[key]: { ...value }}))
		.reduce((p, c) => ({...p, ...c}), {});

	const scAbi = new SmartContractAbi(AbiRegistry.create({
		...abiJson,
		types,
	}));
```

Also you can do it manually in json file.

**Comment by janniksam** [comment]
I'm having the same problem currently.

**Comment by janniksam** [comment]
I'm having the same problem currently.

Please note that its working fine in Firefox, but not in Chrome and Brave.

**Comment by janniksam** [comment]
> Just in case, if someone have this issue and you need to quickfix it before release v12 then you can move your dependent types after independents in property "types" of abi json. In my case it was enums so I sort types to move enums before structs.
> 
> ```
> 	const types = Object.entries(abiJson.types)
> 		.sort(([key, value]) => value.type !== 'enum' ? 1 : -1)
> 		.map(([key, value]) => ({[key]: value}))
> 		.reduce((p, c) => ({...p, ...c}), {});
> 
> 	const scAbi = new SmartContractAbi(AbiRegistry.create({
> 		...abiJson,
> 		types,
> 	}));
> ```
> 
> Also you can do it manually in json file.

@chvarkov Your solution is not working in my case, because NftData is not an enum but also a struct in my case.
Moving the NftData struct before the AuctionItem solves my problems, but I have no idea how this can be done automatically.

**Comment by andreibancioiu** [comment]
@chvarkov, @janniksam, @nvergez, thank you for the details and for bringing this into attention again :tada: 

We are working on a different fix in https://github.com/multiversx/mx-sdk-js-core/pull/256. We are attempting to remove the existing sorting logic (and which was actually fixed in the non-released v12, in PR #224 by @nvergez).

If everything goes well, we might stick to this solution (without any sorting). Otherwise, we will apply @nvergez's patch in v11, as well.

Thank you for your understanding :pray:

**Comment by janniksam** [comment]
Do you have any Idea why it is browser dependent?

**Comment by andreibancioiu** [comment]
> Do you have any Idea why it is browser dependent?

My assumption would be, since the current / previous sorting wasn't complete and stable: accidentally fortunate sorting in Node / Firefox (by chance, it was also a topographic one) on one hand; accidentally unfortunate sorting in other browsers.

https://github.com/multiversx/mx-sdk-js-core/blob/main/src/smartcontracts/typesystem/abiRegistry.ts#L52
